# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='城市名称')),
                ('add_time', models.CharField(default=datetime.datetime.now, max_length=20, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '城市',
                'verbose_name': '城市',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='课程机构')),
                ('category', models.CharField(choices=[('training_org', '培训机构'), ('school', '高校'), ('personal', '个人')], max_length=20)),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='机构图片')),
                ('address', models.CharField(max_length=100, verbose_name='机构地址')),
                ('description', models.TextField(verbose_name='机构介绍')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('favor_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.City', verbose_name='所在城市')),
            ],
            options={
                'verbose_name_plural': '课程机构',
                'verbose_name': '课程机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='教师图片')),
                ('work_year', models.IntegerField(blank=True, null=True, verbose_name='工作年限')),
                ('work_position', models.CharField(blank=True, max_length=20, null=True, verbose_name='工作职位')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('introduction', models.CharField(max_length=100, verbose_name='教师描述')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('favor_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, max_length=20, verbose_name='添加时间')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构')),
            ],
            options={
                'verbose_name_plural': '讲师',
                'verbose_name': '讲师',
            },
        ),
    ]
