# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20171112_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=50, verbose_name='添加时间'),
        ),
    ]
