# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20171112_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='address',
            field=models.CharField(max_length=100, verbose_name='机构详细地址'),
        ),
    ]
