# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_courseorg_students_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='', max_length=10, verbose_name='性别'),
        ),
    ]
