# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='company',
            field=models.CharField(default='', max_length=20, verbose_name='就职公司'),
        ),
    ]
