# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_teacher_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='courses_num',
            field=models.CharField(default=0, max_length=5, verbose_name='课程数目'),
        ),
    ]
