# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_courseorg_courses_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nick_name',
            field=models.CharField(default='', max_length=10, verbose_name='昵称'),
        ),
    ]
