# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_teacher_favor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='favor_id',
            new_name='favor_user_id',
        ),
    ]
