# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20171120_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='favor_user_id',
        ),
    ]
