# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_remove_teacher_favor_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='has_favor',
        ),
    ]
