# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_remove_teacher_has_favor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='城市',
        ),
        migrations.AlterModelTable(
            name='courseorg',
            table='课程机构',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='教师',
        ),
    ]
