# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20171118_2021'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursecomments',
            table='用户课程评论',
        ),
        migrations.AlterModelTable(
            name='userask',
            table='用户咨询',
        ),
        migrations.AlterModelTable(
            name='usercourses',
            table='用户课程',
        ),
        migrations.AlterModelTable(
            name='userfavorite',
            table='用户收藏',
        ),
        migrations.AlterModelTable(
            name='usermessages',
            table='用户消息',
        ),
    ]
