# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recommend',
            field=models.BooleanField(default=False, max_length=2, verbose_name='是否推荐'),
        ),
    ]
