# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_favor',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
    ]
