# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20171122_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter', verbose_name='所属章节'),
        ),
        migrations.AlterModelTable(
            name='chapter',
            table='章节',
        ),
        migrations.AlterModelTable(
            name='course',
            table='课程',
        ),
        migrations.AlterModelTable(
            name='courseresource',
            table='课程资源下载',
        ),
        migrations.AlterModelTable(
            name='video',
            table='视频',
        ),
    ]
