# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverifyrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
