# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171111_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='生日'),
        ),
    ]
